### ISSUE TITLE
Modification de texte lors de l'installation sur la mise à jour de la liste des paquets

### ISSUE THREAD

**Issue by adenis-tis** [tranquilit/WAPT-archives#1]
Lors de l'installation, une option est proposée pour "Lancer la mise à jour des paquets après l"installation" de wapt.exe, or il s'agit de la mise à jour de la liste de paquets (voir copie d'écran ci-joint)

version de WAPT : 0.6.9

![wapt067-install-7-wizard4](https://f.cloud.github.com/assets/2338119/385145/0791d90e-a677-11e2-8c3e-2f9103fbcd53.png)

**Comment by htouvet** [comment]
Translated to english in 0.6.16
