### ISSUE TITLE
message dans waptconsole lors des imports de paquets

### ISSUE THREAD

**Issue by laurent77390** [tranquilit/WAPT-archives#15]
Bonjour à tous,
J'ai un probleme concernant le telechargement de paquets depuis l'onglet "importer depuis internet.
J'ai un message d'erreur :" "is an invalid integer"

J'ai installé la version 1.3.5 de wapt server sur un debian 8.2.0 en VM depuis hyperV sous windows 10 dans l'idee de faire des tests, avec 2 clients, sous windows 2008 R2 et windows 10...

L'installation s'est bien passée mais je suis arrivé à l'etape ou je dois telecharger des paquets pour les deployer, mais je suis bloqué....
![erreur wapt](https://cloud.githubusercontent.com/assets/16702491/12324164/19edbe0e-bac1-11e5-85c5-e13de9f91d8d.png)
merci beaucoup votre aide...

Laurent

**Comment by htouvet** [comment]
définition de proxy incorrecte.
mettre http://monproxy:3128
