### ISSUE TITLE
wapt-get add-upgrade-shutdown fails

### ISSUE THREAD

**Issue by jf-guillou** [tranquilit/WAPT-archives#24]
Hello,

I'm trying to setup waptexit task but the GPO waptdeploy with flag "autoUpgradePolicy" wasn't properly applying.

After some investigation, even the command `wapt-get add-upgrade-shutdown` fails with
`FATAL ERROR : IndexError : list index out of range`

This is probably due to this part of the code : https://github.com/tranquilit/WAPT/blob/f4c4c7a60de34e5c27cf23875a8d7f08565b775b/setuphelpers.py#L1874

We do have a guid group of 3 guids (snip' for readability) :
`[{35378EAC-}{C5120366-}{D02B1F72-}][{A9B8D792-}{0F6B957D-}]`

Those are working properly, the assumption `fix malformed array : should be a list of pairs [{i1}{i2}][{j1}{j2}][{k1}{k2}]` may not be true.

See https://technet.microsoft.com/en-us/library/cc978247.aspx

> The format is: `[{< GUID of client-side extension >}{< GUID of MMC extension >}{< GUID of second MMC extension if appropriate >}][repeat first section as appropriate].`

Thanks !

**Comment by jf-guillou** [comment]
See https://technet.microsoft.com/en-us/library/cc978247.aspx

`The format is: [{< GUID of client-side extension >}{< GUID of MMC extension >}{< GUID of second MMC extension if appropriate >}][repeat first section as appropriate].`

**Comment by jf-guillou** [comment]
Another issue in the same code area : gPCMachineExtensionNames guids should always be in sorted order.

See https://social.msdn.microsoft.com/Forums/en-US/70264a14-579e-4064-887d-4d3743af9a29/msgpol-incorrect-description-for-gpcmachineextensionnames-and-maybe-gpcuserextensionnames

> I had a discussion with Product Group and they confirmed that the CSE guids need to be in sorted order otherwise processing stops at the one that is out of sequence.

In the previous exemple, `add_shutdown_script()` will simply append the waptexit guid group :
`[{35378EAC-}{C5120366-}{D02B1F72-}][{A9B8D792-}{0F6B957D-}][{42B5FAAE-}{40B6664F-}]`
but the chain is not processed and stops before the last group (the waptexit one).
It should be :
`[{35378EAC-}{C5120366-}{D02B1F72-}][{42B5FAAE-}{40B6664F-}][{A9B8D792-}{0F6B957D-}]`

You may want to look at WPKG-GP implementation : https://github.com/cleitet/wpkg-gp/blob/4184201d52cf465bd3b3501e899c69dc8c13e36f/src/WpkgLGPUpdater.py#L69

**Comment by htouvet** [comment]
Thanks.
